### ISSUE TITLE
Differences with grommet/components/icons

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet-icons#1]
Are there differences with the icons included with grommet ?

Sorry for opening an issue on this question - please let me know if there is an alternative way to ask questions

**Comment by karatechops** [comment]
@atanasster feel free to join us on our [Slack channel](http://slackin.grommet.io/)! The icons are being extracted to their own library. @alansouzati may be able to provide a clearer answer but this repo/package is in preparation for Grommet 2.0.

**Comment by atanasster** [comment]
thanks, joined :)

**Comment by RyanCCollins** [comment]
@atanasster to add a bit of context, Grommet 2.0 is a complete refactor of grommet.  We are taking it as an opportunity to reorganize the library and intend to remove the icons from the core library.  The icons, as far as I know, will remain the same but will be in their own separate library. Grommet 1.x will not be affected by this change.

I hope that this helps clarify!  

P.S. in order to clear up the grommet backlog, I am going to go ahead and close this convo.    Please feel free to keep the convo going in here if you have any further questions.

**Comment by atanasster** [comment]
@RyanCCollins - thank you very much for the info. I needed a few icons and went ahead implementing them in Grommet 1.xx, although icons 2.x code looks much nicer. Do you accept icons contributions, and if so - format 2.x, 1.x or both?

**Comment by alansouzati** [comment]
@atanasster thanks for your interest in this project. This is our first official release using [styled-components](https://www.styled-components.com).

Contributions are definitely welcome. It is up to you which repo to contribute to. As @RyanCCollins said, we will be removing the icons from the core library very soon. So I would focus on new contributions on this repository.

We should probably write a `CONTRIBUTING.md` describing the steps for folks interested in sending new icons. I know @L0ZZI has some criteria, here are some I can remember:

0) Icon needs to be an svg
1) The icon needs to be pixel perfect
2) It cannot use body parts
3) It has to be 24x24 view box. All our icons follow the same guideline. Check one example [here](https://raw.githubusercontent.com/grommet/grommet-icons/master/public/img/bus.svg)
4) The icon should not have any background
5) Optimally the icon should have only one compounded path.
6) The icon should only use stroke or fill. Preferably only stroke.

In terms of implementation, we have how to build in the `README.md`. You should include your icon inside `public/img` as a raw svg. The process the generate the icon as a React component is available [here](https://github.com/grommet/grommet-icons/blob/master/tools/generate-icons.js). After you add the raw svg, you can run the following commands:

1 - `num run generate-icons` (this will update the `src/js/icons`)
2 - `npm run test-update` (runs the tests in update mode since you added a new icon)
3 - Review the updated snapshots to make sure your icon has been added.
4 - Send the pull request

If you are only adding one icon, I expect at least 4 files to be changed:

1) Added the raw svg
2) Added the icon as a React component (automated)
3) Updated `src/js/icons/index.js` to include the export for the new icon (automated)
4) Updated test snapshot file including the new icon (automated, after you run test in update mode)

Hope it helps and thanks for your interest in contributing back to Grommet.
