### ISSUE TITLE
Icon for "Data Management"

### ISSUE THREAD

**Issue by vldmr1986** [grommet/grommet-icons#278]
The new design has an icon that I could not find<img width="340" alt="Screenshot 2022-07-25 at 11 28 16" src="https://user-images.githubusercontent.com/17574496/180746329-da4827be-616a-4aae-8e71-96ed8a9d52a0.png">

**Comment by jcfilben** [comment]
Hi @vldmr1986 this icon is the `Gateway` icon. You can see it in use here: https://codesandbox.io/s/grommet-v2-template-forked-5hwy6o?file=/index.js. This icon isn't showing up correctly on the grommet icons site which is why I'm guessing it was difficult to find. We have a separate issue open for icons not displaying correctly on the site https://github.com/grommet/grommet-icons/issues/275.

**Comment by vldmr1986** [comment]
@jcfilben  Thank you
