### ISSUE TITLE
Add document help icon

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet-icons#309]
## Tasks

- confirm with Chris that we want to go this direction first
- add to grommet-icons
- add to Figma and rename as needed

## Initial Notes

Slack thread: https://hpe-internal.slack.com/archives/C04T9NHPDJS/p1679921888486149

Figma: https://www.figma.com/file/lO9SS8xsx1uS42mUw2lLyJ/In-App-Contextual-Help?node-id=5950-84462&t=1LM9LwlYC0zXxAyk-0

![Screen Shot 2023-03-27 at 7 56 17 AM](https://user-images.githubusercontent.com/11637956/227997915-95c4c305-4265-4bf4-8904-4ae6c96f250e.png)

**Comment by jcfilben** [comment]
Update 3/31: I reached out to Chris to confirm that this is the direction we want to go before I add this to grommet-icons

**Comment by jcfilben** [comment]
Update 4/5: I got a response from Gina on Monday that icon is the direction they want to head. Then I heard back from Chris this morning to hold off on adding this icon and he thinks that an existing help icon could be used here. He said he will talk with her today.

**Comment by jcfilben** [comment]
Update 4/7: 🟡 (may not be completed by end of sprint) - I reached out to Chris again this morning but I am still waiting to hear back

**Comment by jcfilben** [comment]
Heard back from Chris, they are looking at updating the ‘catalog’ and ‘search’ icon instead of using the document help icon. I think we can close this issue. At this point I don't think we need to add the document help icon.

The revised search and catalog icon work can be tracked here: https://github.com/grommet/grommet-icons/issues/311
