### ISSUE TITLE
Size and color seems broken or incomplete.

### ISSUE THREAD

**Issue by nogever** [grommet/grommet-icons#53]
The `size` and `color` props seems broken or incomplete.
Here's code: https://codesandbox.io/s/0x65rprz9l
and screenshot
<img width="800" alt="screen shot 2018-07-09 at 6 14 41 pm" src="https://user-images.githubusercontent.com/3888294/42478770-fbcc6124-83a3-11e8-9640-4fb2070e8007.png">

No `'medium'` size and no theme colors like 'brand' and 'status-critical'
Or is this not how I am supposed to use?
Any help appreciated. Thanks!

**Comment by ericsoderberghp** [comment]
Colors like 'brand' and 'status-critical' are grommet colors. So, you would need to be using the icons inside a `<Grommet />` context.

Regarding sizes, grommet-icons only comes with 'large' and 'xlarge'. If a size is not specified, that will be the equivalent of 'medium'. We don't use smaller sizes because most of the icons don't scale well below 24px.

**Comment by RyanCCollins** [comment]
@nogever && @ericsoderberghp 

I've been chatting with Eric about this issue, it turns out that this is a problem we are facing in OneSphere, the result being that icons that are rendered by controls (i.e. Menu) ignore the theme.  In our app, we are extending the HPE theme with a few custom properties.  The result is that the icons ignore the color prop and render as gray even when given the brand color.  In OneSphere this has resulted in us implementing a global style hack so that icons show up the correct color.

**Comment by ericsoderberghp** [comment]
This appears to be related to three things:
- updating react and react-dom to 16.4 to pick up a fix for a context issue
- updating grommet-icons to 2.0.0
- using the `import { Add } from 'grommet-icons';` import format
If these three are followed, things work correctly. I am still investigating why #3 is necessary.
